### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by isty2e**

### CODE REVIEW

**Comment by Shadowrabbit** [comment]
thx

**Comment by Shadowrabbit** [comment]
hi, could you post your steam url here. I want to add it to credit

**Comment by isty2e** [comment]
Uh, what do you mean by steam URL? "Korean by inbae." is already fine enough, I think?

**Comment by Shadowrabbit** [comment]
i want to attach it to you profile. In fact, there are many inbae, i don't know which one is you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shadowrabbit/FactionalWar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 下午3:54
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Shadowrabbit/FactionalWar] Korean translation (#5)





 
Uh, what do you mean by steam URL? "Korean by inbae." is already fine enough, I think?

**Comment by isty2e** [comment]
https://steamcommunity.com/profiles/76561198035343782/

**Comment by Shadowrabbit** [comment]
thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shadowrabbit/FactionalWar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 下午4:48
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Shadowrabbit/FactionalWar] Korean translation (#5)





 
https://steamcommunity.com/profiles/76561198035343782/

**Pull request merged**
